### ISSUE TITLE
请教一下网站的规则如何抓取

### ISSUE THREAD

**Issue by wobushiafa** [HXHGTS/Netch-Rules#1]
您分享的Twitch规则,我使用后发现google,youtube等都能访问,我也试过提取UU的Twitch规则,但是使用它的规则无法打开Twitch,想向您请教一下如何抓取特定网站的规则

**Comment by HXHGTS** [comment]
检查一下是不是没有启用网卡模式，加速器默认是进程代理模式，路由表没有变

**Comment by wobushiafa** [comment]
是用的tun,从UU提取的Twitch规则,但是无法打开Twitch,我是想只加速某一特定的网站

**Comment by HXHGTS** [comment]
可能是UU的Twitch规则需要配合代理技术实现才能正常使用，这样的话它的规则也许不全
