### ISSUE TITLE
请教一下作者关于延迟的问题

### ISSUE THREAD

**Issue by HarukaKaede** [HXHGTS/Netch-Rules#4]
玩使命召唤16的时候偶尔会在比赛中期突然跳到200多ping，直到赛局结束。不知道是设置问题还是Netch的问题。
还有就是能不能请作者弄一个使命召唤17的规则，谢谢。

**Comment by HXHGTS** [comment]
17的规则弄上去了

**Comment by HXHGTS** [comment]
突然跳ping基本上是网络问题
